apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.ports.port}}
          volumeMounts:
            - name: env-js
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: env-js
          configMap:
            name: {{ .Values.configMap.name }}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
