apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{.Values.namespace}}
data:
  default.conf: |
    server {
        listen 80;

        # frontend
        location / {
            root      /usr/share/nginx/html;
            try_files $uri                  $uri/ /index.html;
        }

        location /spring-boot-backend/ {
            proxy_pass http://{{.Values.backend.name}}:{{.Values.backend.port}}/;
            rewrite    ^/{{.Values.backend.name}}/(.*)$      /$1 break;

            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_connect_timeout 30s;
            proxy_send_timeout    30s;
            proxy_read_timeout    30s;
        }
    }
