appName: react-frontend

namespace: dev
image:
  name: tanle92/react-app
  tag: main-b2bc56f

service:
  ports:
    port: 80
    nodePort: 30300

backend:
  name: spring-boot-backend
  port: 8888

configMap:
  name: react-env-config
